### 회원가입
POST http://localhost:8888/api/users/auth/signup
Content-Type: application/json

{
  "loginId": "bruuni",
  "password": "qwer1234@"
}

### 로그인
POST http://localhost:8888/api/users/auth/login
Content-Type: application/json

{
  "loginId": "bruuni",
  "password": "qwer1234@"
}
